# Generated by Django 5.0.6 on 2024-06-21 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='products',
            new_name='product',
        ),
    ]
