# Generated by Django 5.0.6 on 2024-06-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_product_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='index',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
