# Generated by Django 5.0.6 on 2024-06-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_otp_user_otp_password_otp_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address',
            new_name='addressOne',
        ),
        migrations.AddField(
            model_name='customuser',
            name='addressTwo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
