# Generated by Django 5.0.6 on 2024-06-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
