# Generated by Django 5.0.6 on 2024-07-01 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_review_created_at_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarianOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='variant',
            name='optionname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.varianoption'),
        ),
    ]
