# Generated by Django 5.0.6 on 2024-07-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_varianoption_variant_optionname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='optionname',
        ),
        migrations.DeleteModel(
            name='VarianOption',
        ),
    ]
