# Generated by Django 5.0.6 on 2024-07-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_alter_address_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
