# Generated by Django 5.0.6 on 2024-07-05 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_cart_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_amount',
        ),
    ]
