# Generated by Django 5.0.6 on 2024-07-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
