# Generated by Django 5.0.6 on 2024-07-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
